source 'https://rubygems.org'

#gem 'bundler', '1.7.3'
gem 'cucumber', '1.3.17'
gem 'gherkin', '2.12.2'
gem 'rspec', '<3.0.0'
gem 'page-object', '1.0.2'
gem 'selenium-webdriver', '2.43'
gem 'watir-webdriver', '0.6.11'

